import json
import pytest
from unittest.mock import Mock, patch
from std_msgs.msg import ByteMultiArray
from sha3_hasher.ros2_node import HashingNode
from std_msgs.msg import String
from rclpy.node import Node
from rclpy.context import Context
from rclpy.qos import QoS
from rclpy.executors import SingleThreadedExecutor
from rclpy import init, shutdown
from rclpy.utilities import get_default_context
import rclpy

def test_node_initialization():
    context = get_default_context()
    with patch('rclpy.init') as mock_init, patch('rclpy.create_node') as mock_create:
        node = HashingNode.__new__(HashingNode)
        node.get_logger().info = Mock()
        node.create_publisher = Mock()
        node.create_subscription = Mock()
        node.publisher_ = Mock()
        node.subscription = Mock()
        node.publisher_ = Mock(return_value=node)
        node.subscription = Mock(return_value=node)
        node.publish = Mock()
        node.get_name = Mock(return_value='sha3_hasher_node')
        node.get_context = Mock(return_value=context)
        node.create_timer = Mock()
        node.create_subscription = Mock()
        node.create_publisher = Mock()
        node.get_name = Mock()
        node.get_namespace = Mock()
        node.get_namespace_ = Mock()
        node.get_parameters = Mock()
        node.set_parameters = Mock()
        node.add_on_set_parameters_callback = Mock()
        node.get_clock = Mock()
        node.get_logger = Mock()
        node.get_node_names = Mock()
        node.get_node_names_and_namespaces = Mock()
        node.get_topic_names_and_types = Mock()
        node.get_service_names_and_types = Mock()
        node.get_services = Mock()
        node.get_service_names = Mock()
        node.get_service_type = Mock()
        node.get_topic_names = Mock()
        node.get_topic_names_and_types = Mock()
        node.get_topic_types = Mock()
        node.get_topic_names = Mock()
        node.get_topic_names_and_namespaces = Mock()
        node.get_topic_names = Mock()
        node.get_topic_names_and_types = Mock()
        node.get_topic_types = Mock()
        node.get_topic_names = Mock()
        node.get_topic_names_and_namespaces = Mock()
        node.get_topic_names_and_types = Mock()
        node.get_topic_names = Mock()
        node.get_topic_names_and_types = Mock()
        node.get_topic_names = Mock()
        node.get_topic_names_and_namespaces = Mock()
        node.get_topic_names_and_types = Mock()
        node.get_topic_names = Mock()
        node.get_topic_names_and_types = Mock()
        node.get_topic_names = Mock()
        node.get_topic_names_and_namespaces = Mock()
        node.get_topic_names_and_types = Mock()
        node.get_topic_names = Mock()
        node.get_topic_names_and_namespaces = Mock()
        node.get_topic_names = Mock()
        node.get_topic_names_and_namespaces = Mock()
        node.get_topic_names = Mock()
        node.get_topic_names_and_namespaces = Mock()
        node.get_topic_names = Mock()
        node.get_topic_names_and_namespaces = Mock()
        node.get_topic_names = Mock()
        node.get_topic_names_and_namespaces = Mock()
        node.get_topic_names = Mock()
        node.get_topic_names_and_namespaces = Mock()
        node.get_topic_names = Mock()
        node.get_topic_names_and_namespaces = Mock()
        node.get_topic_names = Mock()
        node.get_topic_names_and_namespaces = Mock()
        node.get_topic_names = Mock()
        node.get_topic_names_and_namespaces = Mock()
        node.get_topic_names = Mock()
        node.get_topic_names_and_namespaces = Mock()
        node.get_topic_names = Mock()
        node.get_topic_names_and_namespaces = Mock()
        node.get_topic_names = Mock()
        node.get_topic_names_and_namespaces = Mock()
        node.get_topic_names = Mock()
        node.get_topic_names_and_namespaces = Mock()
        node.get_topic_names = Mock()
        node.get_topic_names_and_namespaces = Mock()
        node.get_topic_names = Mock()
        node.get_topic_names_and_namespaces = Mock()
        node.get_topic_names = Mock()
        node.get_topic_names_and_namespaces = Mock()
        node.get_topic_names = Mock()
        node.get_topic_names_and_names