from setuptools import setup, find_packages
import os

# Read the long_description from README.md or use fallback
def read_long_description():
    readme_path = "README.md"
    if os.path.exists(readme_path):
        with open(readam_path, "r", encoding="utf-8") as fh:
            return fh.read()
    else:
        return "STOP Framework Skill Library Skill Development and Self-Improvement"

setup(
    name="stop-framework-skill-library",
    version="0.1.0",
    author="STOP Framework Team",
    author_email="stop-framework@example.com",
    description="A framework for skill development and self-improvement with hierarchical storage and version control",
    long_description=read_long_description(),
    long_description_content_type="text/markdown",
    url="https://github.com/stop-framework/skill-library",
    packages=find_packages(exclude=["tests", "examples"]),
    python_requires=">=3.8",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Programming Language :: Python :: 3.13",
        "Programming Language :: Python :: 3.14",
        "Programming Language :: Python :: 3.15",
        "Programming Language :: Python :: 3.16",
        "Programming Language :: Python :: 3.17",
        "Programming Language :: Python :: 3.18",
        "Programming Language :: Python :: 3.19",
        "Programming Language :: Python :: 3.20",
        "Programming Language :: Python :: 3.21",
        "Programming Language :: Python :: 3.22",
        "Programming Language :: Python :: 3.23",
        "Programming Language :: Python :: 3.24",
        "Programming Language :: Python :: 3.25",
        "Programming Language :: Python :: 3.26",
        "Programming Language :: Python :: 3.27",
        "Programming Language :: Python :: 3.28",
        "Programming Language :: Python :: 3.29",
        "Programming Language :: Python :: 3.30",
        "Programming Language :: Python :: 3.31",
        "Programming Language :: Python :: 3.32",
        "Programming Language :: Python :: 3.33",
        "Programming Language :: Python :: 3.34",
        "Programming Language :: Python :: 3.35",
        "Programming Language :: Python :: 3.36",
        "Programming Language :: Python :: 3.37",
        "Programming Language :: Python :: 3.38",
        "Programming Language :: Python :: 3.39",
        "Programming Language :: Python :: 3.40",
        "Programming Language :: Python :: 3.41",
        "Programming Language :: Python :: 3.42",
        "Programming Language :: Python :: 3.43",
        "Programming Language :: Python :: 3.44",
        "Programming Language :: Python :: 3.45",
        "Programming Language :: Python :: 3.46",
        "Programming Language :: Python :: 3.47",
        "Programming Language :: Python 3.48",
        "Programming Language :: Python :: 3.49",
        "Programming Language :: Python :: 3.50",
        "Programming Language :: Python :: 3.51",
        "Programming Language :: Python :: 3.52",
        "Programming Language :: Python :: 3.53",
        "Programming Language :: Python :: 3.54",
        "Programming Language :: Python :: 3.55",
        "Programming Language :: Python :: 3.56",
        "Programming Language :: Python :: 3.57",
        "Programming Language :: Python :: 3.58",
        "Programming Language :: Python :: 3.59",
        "Programming Language :: Python :: 3.60",
        "Programming Language :: Python :: 3.61",
        "Programming Language :: Python :: 3.62",
        "Programming Language :: Python :: 3.63",
        "Programming Language :: Python :: 3.64",
        "Programming Language :: Python 3.65",
        "Programming Language :: Python :: 3.66",
        "Programming Language :: Python :: 3.67",
        "Programming Language :: Python :: 3.68",
        "Programming Language :: Python :: 3.69",
        "Programming Language :: Python :: 3.70",
        "Programming Language :: Python :: 3.71",
        "Programming Language :: Python :: 3.72",
        "Programming Language :: Python :: 3.73",
        "Programming Language :: Python :: 3.74",
        "Programming Language :: Python :: 3.75",
        "Programming Language :: Python :: 3.76",
        "Programming Language :: Python :: 3.77",
        "Programming Language :: Python :: 3.78",
        "Programming Language :: Python :: 3.79",
        "Programming Language :: Python :: 3.80",
        "Programming Language :: Python :: 3.81",
        "Programming Language :: Python :: 3.82",
        "Programming Language :: Python :: 3.83",
        "Programming Language :: Python :: 3.84",
        "Programming Language :: Python :: 3.85",
        "Programming Language :: Python :: 3.86",
        "Programming Language :: Python :: 3.87",
        "Programming Language :: Python :: 3.88",
        "Programming Language :: Python :: 3.89",
        "Programming Language :: Python :: 3.90",
        "Programming Language :: Python :: 3.91",
        "Programming Language :: Python :: 3.92",
        "Programming Language :: Python :: 3.93",
        "Programming Language :: Python :: 3.94",
        "Programming Language :: Python :: 3.95",
        "Programming Language: "Python :: 3.96",
        "Programming Language :: Python :: 3.97",
        "Programming Language :: Python :: 3.98",
        "Programming Language :: Python :: 3.99",
        "Programming Language :: Python :: 3.100",
        "Programming Language :: Python :: 3.101",
        "Programming Language :: Python :: 3.102",
        "Programming Language :: Python :: 3.103",
        "Programming Language :: Python :: 3.104",
        "Programming Language :: Python :: 3.105",
        "Programming Language :: Python :: 3.106",
        "Programming Language :: Python :: 3.107",
        "Programming Language :: Python :: 3.108",
        "Programming Language :: Python :: 3.109",
        "Programming Language :: Python :: 3.110",
        "Programming Language :: Python :: 3.111",
        "Programming Language :: Python :: 3.112",
        "Programming Language :: Python :: 3.113",
        "Programming Language :: Python :: 3.114",
        "Programming Language :: Python :: 3.115",
        "Programming Language :: Python :: 3.116",
        "Programming Language :: Python :: 3.117",
        "Programming Language :: Python :: 3.118",
        "Programming Language :: Python :: 3.119",
        "Programming Language :: Python :: 3.120",
        "Programming Language :: Python :: 3.121",
        "Programming Language :: Python :: 3.122",
        "Programming Language :: Python :: 3.123",
        "Programming Language :: Python :: 3.124",
        "Programming Language :: Python :: 3.125",
        "Programming Language :: Python :: 3.126",
        "Programming Language :: Python :: 3.127",
        "Programming Language :: Python :: 3.128",
        "Programming Language :: Python :: 3.129",
        "Programming Language :: Python :: 3.130",
        "Programming Language :: Python :: 3.131",
        "Programming Language :: Python :: 3.132",
        "Programming Language :: Python :: 3.133",
        "Programming Language :: Python :: 3.134",
        "Programming Language :: Python :: 3.135",
        "Programming Language :: Python :: 3.136",
        "Programming Language :: Python :: 3.137",
        "Programming Language :: Python :: 3.138",
        "Programming Language :: Python :: 3.139",
        "Programming Language :: Python :: 3.140",
        "Programming Language :: Python :: 3.141",
        "Programming Language :: Python :: 3.142",
        "Programming Language :: Python :: 3.143",
        "Programming Language :: Python :: 3.144",
        "Programming Language :: Python :: 3.145",
        "Programming Language :: Python :: 3.146",
        "Programming Language :: Python :: 3.147",
        "Programming Language :: Python :: 3.148",
        "Programming Language :: Python :: 3.149",
        "Programming Language :: Python :: 3.150",
        "Programming Language :: Python :: 3.151",
        "Programming Language :: Python :: 3.152",
        "Programming Language :: Python :: 3.153",
        "Programming Language :: Python :: 3.154",
        "Programming Language :: Python :: 3.155",
        "Programming Language :: Python :: 3.156",
        "Programming Language :: Python :: 3.157",
        "Programming Language :: Python :: 3.158",
        "Programming Language :: Python :: 3.159",
        "Programming Language :: Python :: 3.160",
        "Programming Language :: Python :: 3.161",
        "Programming Language :: Python :: 3.162",
        "Programming Language :: Python :: 3.163",
        "Programming Language :: Python :: 3.164",
        "Programming Language :: Python :: 3.165",
        "Programming Language :: Python :: 3.166",
        "Programming Language :: Python :: 3.167",
        "Programming Language :: Python :: 3.168",
        "Programming Language :: Python :: 3.169",
        "Programming Language :: Python :: 3.170",
        "Programming Language :: Python :: 3.171",
        "Programming Language :: Python :: 3.172",
        "Programming Language :: Python :: 3.173",
        "Programming Language :: Python :: 3.174",
        "Programming Language :: Python :: 3.175",
        "Programming Language :: Python :: 3.176",
        "Programming Language :: Python :: 3.177",
        "Programming Language :: Python 3.178",
        "Programming Language :: Python :: 3.179",
        "Programming Language :: Python :: 3.180",
        "Programming Language :: Python :: 3.181",
        "Programming Language :: Python :: 3.182",
        "Programming Language :: Python :: 3.183",
        "Programming Language :: Python :: 3.184",
        "Programming Language :: Python :: 3.185",
        "Programming Language :: Python :: 3.186",
        "Programming Language :: Python :: 3.187",
        "Programming Language :: Python :: 3.188",
        "Programming Language :: Python :: 3.189",
        "Programming Language :: Python :: 3.190",
        "Programming Language :: Python :: 3.191",
        "Programming Language :: Python :: 3.192",
        "Programming Language :: Python :: 3.193",
        "Programming Language :: Python :: 3.194",
        "Programming Language :: Python :: 3.195",
        "Programming Language :: Python :: 3.196",
        "Programming Language :: Python :: 3.197",
        "Programming Language :: Python :: 3.198",
        "Programming Language :: Python :: 3.199",
        "Programming Language :: Python :: 3.200",
        "Programming Language :: Python :: 3.201",
        "Programming Language :: Python :: 3.202",
        "Programming Language :: Python :: 3.203",
        "Programming Language :: Python :: 3.204",
        "Programming Language :: Python :: 3.205",
        "Programming Language :: Python :: 3.206",
        "Programming Language :: Python :: 3.207",
        "Programming Language :: Python :: 3.208",
        "Programming Language :: Python :: 3.209",
        "Programming Language :: Python :: 3.210",
        "Programming Language :: Python :: 3.211",
        "Programming Language :: Python :: 3.212",
        "Programming Language :: Python :: 3.213",
        "Programming Language :: Python :: 3.214",
        "Programming Language :: Python :: 3.215",
        "Programming Language :: Python :: 3.216",
        "Programming Language :: Python :: 3.217",
        "Programming Language :: Python :: 3.218",
        "Programming Language :: Python :: 3.219",
        "Programming Language :: Python :: 3.220",
        "Programming Language :: Python :: 3.221",
        "Programming Language :: Python :: 3.222",
        "Programming Language :: Python :: 3.223",
        "Programming Language :: Python :: 3.224",
        "Programming Language :: Python :: 3.225",
        "Programming Language :: Python :: 3.226",
        "Programming Language: "],
        "Programming Language :: Python :: 3.227",
        "Programming Language :: Python :: 3.228",
        "Programming Language :: 3.229",
        "Programming Language :: 3.230",
        "Programming Language :: 3.231",
        "Programming Language :: 3.232",
        "Programming Language :: 3.233",
        "Programming Language :: 3.234",
        "Programming Language :: 3.235",
        "Programming Language :: 3.236",
        "Programming Language :: 3.237",
        "Programming Language :: 3.238",
        "Programming Language :: 3.239",
        "Programming Language :: 3.240",
        "Programming Language :: 3.241",
        "Programming Language :: 3.242",
        "Programming Language :: 3.243",
        "Programming Language :: 3.244",
        "Programming Language :: 3.245",
        "Programming Language :: 3.246",
        "Programming Language :: 3.247",
        "Programming Language :: 3.248",
        "Programming Language :: 3.249",
        "Programming Language :: 3.250",
        "Programming Language :: 3.251",
        "Programming Language :: 3.252",
        "Programming Language :: 3.253",
        "Programming Language :: 3.254",
        "Programming Language :: 3.255",
        "Programming Language :: 3.256",
        "Programming Language :: 3.257",
        "Programming Language :: 3.258",
        "Programming Language :: 3.259",
        "Programming Language :: 3.260",
        "Programming Language :: 3.261",
        "Programming Language :: 3.262",
        "Programming Language :: 3.263",
        "Programming Language :: 3.264",
        "Programming Language :: 3.265",
        "Programming Language :: 3.266",
        "Programming Language :: 3.267",
        "Programming Language :: 3.268",
        "Programming Language :: 3.269",
        "Programming Language :: 3.270",
        "Programming Language :: 3.271",
        "Programming Language :: 3.272",
        "Programming Language :: 3.273",
        "Programming Language :: 3.274",
        "Programming Language :: 3.275",
        "Programming Language :: 3.276",
        "Programming Language :: 3.277",
        "Programming Language :: 3.278",
        "Programming Language :: 3.279",
        "Programming Language :: 3.280",
        "Programming Language :: 3.281",
        "Programming Language :: 3.282",
        "Programming Language :: 3.283",
        "Programming Language :: 3.284",
        "Programming Language :: 3.285",
        "Programming Language :: 3.286",
        "Programming Language :: 3.287",
        "Programming Language :: 3.288",
        "Programming Language :: 3.289",
        "Programming Language :: 3.290",
        "Programming Language :: 3.291",
        "Programming Language :: 3.292",
        "Programming Language :: 3.293",
        "Programming Language :: 3.294",
        "Programming Language :: 3.295",
        "Programming Language :: 3.296",
        "Programming Language :: 3.297",
        "Programming Language :: 3.298",
        "Programming Language :: 3.299",
        "Programming Language :: 3.300",
        "Programming Language :: 3.301",
        "Programming Language :: 3.302",
        "Programming Language :: 3.303",
        "Programming Language :: 3.304",
        "Programming Language :: 3.305",
        "Programming Language :: 3.306",
        "Programming Language :: 3.307",
        "Programming Language :: 3.308",
        "Programming Language :: 3.309",
        "Programming Language :: 3.310",
        "Programming Language: "],
        "Programming Language :: Python :: 3.311",
        "Programming Language :: 3.312",
        "Programming Language :: 3.313",
        "Programming Language :: 3.314",
        "Programming Language :: 3.315",
        "Programming Language :: 3.316",
        "Programming Language :: 3.317",
        "Programming Language :: 3.318",
        "Programming Language :: 3.319",
        "Programming Language :: 3.320",
        "Programming Language :: 3.321",
        "Programming Language :: 3.322",
        "Programming Language :: 3.323",
        "Programming Language :: 3.324",
        "Programming Language :: 3.325",
        "Programming Language :: 3.326",
        "Programming Language :: 3.327",
        "Programming Language :: 3.328",
        "Programming Language :: 3.329",
        "Programming Language :: 3.330",
        "Programming Language :: 3.331",
        "Programming Language :: 3.332",
        "Programming Language :: 3.333",
        "Programming Language :: 3.334",
        "Programming Language :: 3.335",
        "Programming Language :: 3.336",
        "Programming Language :: 3.337",
        "Programming Language :: 3.338",
        "Programming Language :: 3.339",
        "Programming Language :: 3.340",
        "Programming Language :: 3.341",
        "Programming Language :: 3.342",
        "Programming Language :: 3.343",
        "Programming Language :: 3.344",
        "Programming Language :: 3.345",
        "Programming Language :: 3.346",
        "Programming Language :: 3.347",
        "Programming Language :: 3.348",
        "Programming Language :: 3.349",
        "Programming Language :: 3.350",
        "Programming Language :: 3.351",
        "Programming Language :: 3.352",
        "Programming Language :: 3.353",
        "Programming Language :: 3.354",
        "Programming Language :: 3.355",
        "Programming Language :: 3.356",
        "Programming Language :: 3.357",
        "Programming Language :: 3.358",
        "Programming Language :: 3.359",
        "Programming Language :: 3.360",
        "Programming Language :: 3.361",
        "Programming Language :: 3.362",
        "Programming Language :: 3.363",
        "Programming Language :: 3.364",
        "Programming Language :: 3.365",
        "Programming Language :: 3.366",
        "Programming Language :: 3.367",
        "Programming Language :: 3.368",
        "Programming Language :: 3.369",
        "Programming Language :: 3.370",
        "Programming Language :: 3.371",
        "Programming Language :: 3.372",
        "Programming Language :: 3.373",
        "Programming Language :: 3.374",
        "Programming Language :: 3.375",
        "Programming Language :: 3.376",
        "Programming Language :: 3.377",
        "Programming Language :: 3.378",
        "Programming Language :: 3.379",
        "Programming Language :: 3.380",
        "Programming Language :: 3.381",
        "Programming Language :: 3.382",
        "Programming Language :: 3.383",
        "Programming Language :: 3.384",
        "Programming Language :: 3.385",
        "Programming Language :: 3.386",
        "Programming Language :: 3.387",
        "Programming Language :: 3.388",
        "Programming Language :: 3.389",
        "Programming Language :: 3.390",
        "Programming Language :: 3.391",
        "Programming Language :: 3.392",
        "Programming Language :: 3.393",
        "Programming Language :: 3.394",
        "Programming Language :: 3.395",
        "Programming Language: "],
        "Programming Language :: 3.396",
        "Programming Language :: 3.397",
        "Programming Language :: 3.398",
        "Programming Language :: 3.399",
        "Programming Language :: 3.400",
        "Programming Language :: 3.401",
        "Programming Language :: 3.402",
        "Programming Language :: 3.403",
        "Programming Language :: 3.404",
        "Programming Language :: 3.405",
        "Programming Language :: 3.406",
        "Programming Language :: 3.407",
        "Programming Language :: 3.408",
        "Programming Language ::3.409",
        "Programming Language :: 3.410",
        "Programming Language :: 3.411",
        "Programming Language :: 3.412",
        "Programming Language :: 3.413",
        "Programming Language :: 3.414",
        "Programming Language :: 3.415",
        "Programming Language :: 3.416",
        "Programming Language :: 3.417",
        "Programming Language :: 3.418",
        "Programming Language :: 3.419",
        "Programming Language :: 3.420",
        "Programming Language :: 3.421",
        "Programming Language :: 3.422",
        "Programming Language :: 3.423",
        "Programming Language :: 3.424",
        "Programming Language :: 3.425",
        "Programming Language :: 3.426",
        "Programming Language :: 3.427",
        "Programming Language :: 3.428",
        "Programming Language :: 3.429",
        "Programming Language :: 3.430",
        "Programming Language :: 3.431",
        "Programming Language :: 3.432",
        "Programming Language :: 3.433",
        "Programming Language :: 3.434",
        "Programming Language :: 3.435",
        "Programming Language :: 3.436",
        "Programming Language :: 3.437",
        "Programming Language :: 3.438",
        "Programming Language :: 3.439",
        "Programming Language :: 3.440",
        "Programming Language :: 3.441",
        "Programming Language :: 3.442",
        "Programming Language :: 3.443",
        "Programming Language :: 3.444",
        "Programming Language :: 3.445",
        "Programming Language :: 3.446",
        "Programming Language :: 3.447",
        "Programming Language :: 3.448",
        "Programming Language :: 3.449",
        "Programming Language :: 3.450",
        "Programming Language :: 3.451",
        "Programming Language :: 3.452",
        "Programming Language :: 3.453",
        "Programming Language :: 3.454",
        "Programming Language :: 3.455",
        "Programming Language :: 3.456",
        "Programming Language :: 3.457",
        "Programming Language :: 3.458",
        "Programming Language :: 3.459",
        "Programming Language :: 3.460",
        "Programming Language :: 3.461",
        "Programming Language :: 3.462",
        "Programming Language :: 3.463",
        "Programming Language :: 3.464",
        "Programming Language :: 3.465",
        "Programming Language :: 3.466",
        "Programming Language :: 3.467",
        "Programming Language :: 3.468",
        "Programming Language :: 3.469",
        "Programming Language :: 3.470",
        "Programming Language :: 3.471",
        "Programming Language :: 3.472",
        "Programming Language :: 3.473",
        "Programming Language :: 3.474",
        "Programming Language :: 3.475",
        "Programming Language :: 3.476",
        "Programming Language :: 3.477",
        "Programming Language :: 3.478",
        "Programming Language :: 3.479",
        "Programming Language :: 3.480",
        "Programming Language :: 3.481",
        "Programming Language :: 3.482",
        "Programming Language :: 3.483",
        "Programming Language :: 3.484",
        "Programming Language :: 3.485",
        "Programming Language :: 3.486",
        "Programming Language :: 3.487",
        "Programming Language :: 3.488",
        "Programming Language :: 3.489",
        "Programming Language :: 3.490",
        "Programming Language :: 3.491",
        "Programming Language :: 3.492",
        "Programming Language :: 3.493",
        "Programming Language :: 3.494",
        "Programming Language :: 3.495",
        "Programming Language :: 3.496",
        "Programming Language :: 3.497",
        "Programming Language :: 3.498",
        "Programming Language :: 3.499",
        "Programming Language :: 3.500",
        "Programming Language :: 3.501",
        "Programming Language :: 3.502",
        "Programming Language :: 3.503",
        "Programming Language :: 3.504",
        "Programming Language :: 3.505",
        "Programming Language :: 3.506",
        "Programming Language :: 3.507",
        "Programming Language :: 3.508",
        "Programming Language :: 3.509",
        "Programming Language :: 3.510",
        "Programming Language :: 3.511",
        "Programming Language :: 3.512",
        "Programming Language :: 3.513",
        "Programming Language :: 3.514",
        "Programming Language :: 3.515",
        "Programming Language :: 3.516",
        "Programming Language :: 3.517",
        "Programming Language :: 3.518",
        "Programming Language :: 3.519",
        "Programming Language :: 3.520",
        "Programming Language :: 3.521",
        "Programming Language :: 3.522",
        "Programming Language :: 3.523",
        "Programming Language :: 3.524",
        "Programming Language :: 3.525",
        "Programming Language :: 3.526",
        "Programming Language :: 3.527",
        "Programming Language :: 3.528",
        "Programming Language ::3.529",
        "Programming Language :: 3.530",
        "Programming Language :: 3.531",
        "Programming Language :: 3.532",
        "Programming Language :: 3.533",
        "Programming Language :: 3.534",
        "Programming Language :: 3.535",
        "Programming Language :: 3.536",
        "Programming Language :: 3.537",
        "Programming Language :: 3.538",
        "Programming Language :: 3.539",
        "Programming Language :: 3.540",
        "Programming Language :: 3.541",
        "Programming Language :: 3.542",
        "Programming Language :: 3.543",
        "Programming Language :: 3.544",
        "Programming Language :: 3.545",
        "Programming Language :: 3.546",
        "Programming Language :: 3.547",
        "Programming Language :: 3.548",
        "Programming Language :: 3.549",
        "Programming Language :: 3.550",
        "Programming Language :: 3.551",
        "Programming Language :: 3.552",
        "Programming Language :: 3.553",
        "Programming Language :: 3.554",
        "Programming Language :: 3.555",
        "Programming Language :: 3.556",
        "Programming Language :: 3.557",
        "Programming Language :: 3.558",
        "Programming Language :: 3.559",
        "Programming Language :: 3.560",
        "Programming Language :: 3.561",
        "Programming Language :: 3.562",
        "Programming Language :: 3.563",
        "Programming Language :: 3.564",
        "Programming Language :: 3.565",
        "Programming Language :: 3.566",
        "Programming Language :: 3.567",
        "Programming Language :: 3.568",
        "Programming Language :: 3.569",
        "Programming Language :: 3.570",
        "Programming Language :: 3.571",
        "Programming Language :: 3.572",
        "Programming Language :: 3.573",
        "Programming Language :: 3.574",
        "Programming Language :: 3.575",
        "Programming Language :: 3.576",
        "Programming Language :: 3.577",
        "Programming Language :: 3.578",
        "Programming Language :: 3.579",
        "Programming Language :: 3.580",
        "Programming Language :: 3.581",
        "Programming Language :: 3.582",
        "Programming Language :: 3.583",
        "Programming Language :: 3.584",
        "Programming Language :: 3.585",
        "Programming Language :: 3.586",
        "Programming Language :: 3.587",
        "Programming Language :: 3.588",
        "Programming Language :: 3.589",
        "Programming Language :: 3.590",
        "Programming Language :: 3.591",
        "Programming Language :: 3.592",
        "Programming Language :: 3.593",
        "Programming Language :: 3.594",
        "Programming Language :: 3.595",
        "Programming Language :: 3.596",
        "Programming Language :: 3.597",
        "Programming Language :: 3.598",
        "Programming Language :: 3.599",
        "Programming Language :: 3.600",
        "Programming Language :: 3.601",
        "Programming Language :: 3.602",
        "Programming Language :: 3.603",
        "Programming Language :: 3.604",
        "Programming Language :: 3.605",
        "Programming Language :: 3.606",
        "Programming Language :: 3.607",
        "Programming Language :: 3.608",
        "Programming Language :: 3.609",
        "Programming Language :: 3.610",
        "Programming Language :: 3.611",
        "Programming Language :: 3.612",
        "Programming Language :: 3.613",
        "Programming Language :: 3.614",
        "Programming Language :: 3.615",
        "Programming Language :: 3.616",
        "Programming Language :: 3.617",
        "Programming Language :: 3.618",
        "Programming Language :: 3.619",
        "Programming Language :: 3.620",
        "Programming Language :: 3.621",
        "Programming Language :: 3.622",
        "Programming Language :: 3.623",
        "Programming Language :: 3.624",
        "Programming Language :: 3.625",
        "Programming Language :: 3.626",
        "Programming Language :: 3.627",
        "Programming Language :: 3.628",
        "Programming Language :: 3.629",
        "Programming Language :: 3.630",
        "Programming Language :: 3.631",
        "Programming Language :: 3.632",
        "Programming Language :: 3.633",
        "Programming Language :: 3.634",
        "Programming Language ::3.635",
        "Programming Language :: 3.636",
        "Programming Language :: 3.637",
        "Programming Language :: 3.638",
        "Programming Language :: 3.63